### ISSUE TITLE
Fixed value for quality bound

### ISSUE THREAD

**Issue by MFaisalZaki** [aiplan4eu/up-symk#5]
Is there any way to control the quality bound since the code [hard codes it to 1.0](https://github.com/aiplan4eu/up-symk/blob/73170b4b4849ed320b5183b2538d168867e84ce6/up_symk/symk.py#L58)?

**Comment by speckdavid** [comment]
Hi,

Yes and no. Currently, it's not available as a separate parameter. However, you can directly specify your desired search configuration. Here's an example with a different quality bound:

```
number_of_plans= 1000
quality = 1.5
search_config = f"symq-bd(plan_selection=top_k(num_plans={number_of_plans},dump_plans=true),quality={quality})"

plans = []

with AnytimePlanner(name='symk-opt', params={"symk_anytime_search_config": search_config}) as planner:
    for i, result in enumerate(planner.get_solutions(pddl_problem)):
        if result.status == up.engines.PlanGenerationResultStatus.INTERMEDIATE:
            plans.append(result.plan)
        elif result.status in unified_planning.engines.results.POSITIVE_OUTCOMES:
            print(f"{planner.name} found {len(plans)} plans.")
        elif result.status not in unified_planning.engines.results.POSITIVE_OUTCOMES:
            print("No plan found.")
``` 

You can find more information about the search configuration [here](https://github.com/speckdavid/symk). Note that the `dump_plans=true` parameter must be set, otherwise, the UP cannot parse the plans.

**Comment by MFaisalZaki** [comment]
Awesome, thanks @speckdavid.
